[open][neva_upstreamable][lttng] Add LTTng tracepoints support
:Release Notes:
Add LTTng tracepoints support

:Detailed Notes:
Add LTTng tracepoints support

This patch squashes the following patches
from chromium68:

commit d7b77ff7d9178acc5f6f84d27f56c0e714d28e7a (tag: submissions/2)
Author: Andre Rosa <andre.rosa@lge.com>
Date:   Mon Oct 22 11:01:33 2018 -0700

    [open][neva_upstreamable][lttng] Add LTTng tracepoints support

commit d78b0551446bf7685f7c743c4dd09609b4633940
Author: Andre Rosa <andre.rosa@lge.com>
Date:   Tue Jan 29 11:49:04 2019 -0800

    fixup! [open][neva_upstreamable][lttng] Add LTTng tracepoints support

This fixes mksnapshot linking error when building for qemux86:
| FAILED: mksnapshot
...
| obj/v8/v8_base/v8_base_jumbo_4.o:v8_base_jumbo_4.cc:function trace_event_lttng::LttngTraceScope::LttngTraceScope(char const*, char const*): error: undefined reference to '__tracepoint_chromium_tracing___scope_entry'
| obj/v8/v8_base/v8_base_jumbo_4.o:v8_base_jumbo_4.cc:function trace_event_lttng::LttngTraceScope::LttngTraceScope(char const*, char const*): error: undefined reference to 'tracepoint_dlopen_ptr'
| obj/v8/v8_base/v8_base_jumbo_4.o:v8_base_jumbo_4.cc:function trace_event_lttng::LttngTraceScope::~LttngTraceScope(): error: undefined reference to '__tracepoint_chromium_tracing___scope_exit'
| obj/v8/v8_base/v8_base_jumbo_4.o:v8_base_jumbo_4.cc:function trace_event_lttng::LttngTraceScope::~LttngTraceScope(): error: undefined reference to 'tracepoint_dlopen_ptr'
| obj/v8/v8_base/v8_base_jumbo_4.o:v8_base_jumbo_4.cc:function v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*): error: undefined reference to '__tracepoint_chromium_tracing___scope_exit'
| obj/v8/v8_base/v8_base_jumbo_4.o:v8_base_jumbo_4.cc:function v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*): error: undefined reference to 'tracepoint_dlopen_ptr'
| obj/v8/v8_base/v8_base_jumbo_5.o:v8_base_jumbo_5.cc:function v8::internal::Builtin_Impl_Stats_DateNow(int, v8::internal::Object**, v8::internal::Isolate*): error: undefined reference to '__tracepoint_chromium_tracing___scope_exit'
| obj/v8/v8_base/v8_base_jumbo_5.o:v8_base_jumbo_5.cc:function v8::internal::Builtin_Impl_Stats_DateNow(int, v8::internal::Object**, v8::internal::Isolate*): error: undefined reference to 'tracepoint_dlopen_ptr'
| obj/v8/v8_base/v8_base_jumbo_5.o:v8_base_jumbo_5.cc:function v8::internal::Builtin_Impl_Stats_MapPrototypeClear(int, v8::internal::Object**, v8::internal::Isolate*): error: undefined reference to '__tracepoint_chromium_tracing___scope_exit'
| collect2: error: ld returned 1 exit status

:Testing Performed:
Please see http://gpro.lgsvl.com/218744 .
1. Once the board is up, check whether the WAM app process tree is awaken:
   root@LGwebOS:~# ps axf | grep WebAppMgr
2. If awaken, stop the service:
   root@LGwebOS:~# systemctl stop webapp-mgr
3. Then restart manually the WAM binary:
   root@LGwebOS:~# sh -x /lib/systemd/system/scripts/webapp-mgr.sh
4. Verify that there is no more backtrace (with the zygote source code mentioned
   at the top) among the generated logging output

:QA Notes:
Test cases: QR-1235, QR-1245

:Issues Addressed:
[PLAT-65789] Chromium 2018Q4 upgrade: migrate "initial" patchset
[DRD-1045] SVL: Add support for lttng to chromium
[PLAT-10729] Initial mapping of Chromium Tracer in LTTng
[PLAT-67410] [lttng] Chromium 2018Q4 upgrade: migrate "initial" patchset
[PLAT-72894] [chromium68] Zygote process is crashed due to
[PLAT-79954] V8: Port "[open][neva_upstreamable][lttng] Add LTTng tracepoints support"

Change-Id: I1835f9eb4e4d1ba25c1ecbed2f84c49c2e43a2e6
Originally-Reviewed-on: http://gpro.lgsvl.com/220240
Originally-Reviewed-on: http://gpro.lgsvl.com/229290